# Generated by Django 6.0.6 on 2026-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('audience', models.CharField(choices=[('KIDS', 'Kids'), ('ADULTS', 'Adults'), ('GENERAL', 'General')], default='GENERAL', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='books', to='library_app.booksection'),
        ),
    ]
